name: "🙋‍♂️ Question"
description: Create a new ticket for a question.
title: "🙋‍♂️ [QST] - <title>"
labels: [
  "question"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter your question
      placeholder: Short and explicit description of your question...
    validations:
      required: true
